### PR TITLE
Er personal v2

### PR DESCRIPTION
**Pull request by evanreynolds1116**
Updated Header/Nav/Logo + Footer

### CODE REVIEW

**Review by tstrotherIV — COMMENTED** [review]
Looks like a bunch of greatness
👍

**Review by tstrotherIV — COMMENTED** [review]
Looks like a bunch of greatness
👍

**Comment by tannerb9** [comment]
👍

**Review by kirksudduth — APPROVED** [review]
HEHYEAH 👍

**Pull request merged**
